### ISSUE TITLE
Web UI feature request

### ISSUE THREAD

**Issue by shamio** [jncraton/languagemodels#1]
This code looks so good and it would be so nice if we can access it in a web user interface locally instead of using python directly in the DOS mode and typing lm.do(" and such codes. Is there any chance you add this feature to this code and make it something like the demo you've sent in reddit ? (https://jncraton-languagemodels-examplesstreamlitchat-s4uj7z.streamlit.app/)

**Comment by jncraton** [comment]
There are currently two demos with web UIs that you could run locally. They both use Streamlit. You should be able to run them locally as follows:
1. Clone this repository: `git clone https://github.com/jncraton/languagemodels`
2. Install streamlit: `pip3 install streamlit`
3. Run one of the examples: `streamlit run examples/streamlit.py`

**Comment by shamio** [comment]
> 3\. streamlit run examples/streamlit.py

I followed the steps and after running the 3rs step, i get this error:
Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.

Error: Invalid value: File does not exist: examples/streamlit.py

**Comment by jncraton** [comment]
You need the example file to be available at the specified path. You can do that either by cloning this repo and changing to it's root directory, or you can download [the file](https://github.com/jncraton/languagemodels/blob/main/examples/streamlit.py) directly and place it where you'd like. You should then be able to run the file using `streamlit run {file}`.
