### ISSUE TITLE
Commercial Models? (Follow Up)

### ISSUE THREAD

**Issue by GenerativeGuru** [jncraton/languagemodels#23]
Greetings,

Following up from my previous issue, I see you've added [this section](https://github.com/jncraton/languagemodels#commercial-use) on commercial licenses, but I'm struggling to understand what sort of models may be returned by such a command. Do you have a list somewhere? 

My real interest though is in figuring out how to make this work with the orca-3b model. I've played with it using GPT4All and llama (my goal is CPU inference on my Intel MacBook Pro) but I like your implementation the best. 

I've tried looking into things, and it looks like you're using something called ctransformers2, but it's all a bit over my head still. Can you help dumb down some high level instructions I could do if I wanted to get orca-3b working with this?

**Comment by jncraton** [comment]
> I'm struggling to understand what sort of models may be returned by such a command. Do you have a list somewhere?

This isn't well documented at the moment, but there is a [list of all supported models](https://github.com/jncraton/languagemodels/blob/fdec0e6171cf48d2c0b0f5b91a9a2fd5051ec0bc/languagemodels/models.py#L12-L142) in the source code. Right now, you'll get FLAN-T5 models if you use the regex filter from the readme.

> My real interest though is in figuring out how to make this work with the orca-3b model.

I'm assuming that you are talking about [orca-mini-3b](https://huggingface.co/psmathur/orca_mini_3b). This should work with CTranslate2 relatively easily, as it is an OpenLLaMA fine-tune, but I haven't personally used the 3B LLaMA models with CTranslate2. It should work almost exactly like the other generative models. There's are several [examples](https://opennmt.net/CTranslate2/guides/transformers.html#gpt-2) in the CTranslate2 documentation.
