### ISSUE TITLE
lm.extract_answer method is failing 

### ISSUE THREAD

**Issue by TheChoicists** [jncraton/languagemodels#26]
Hello Team, 

When I execute lm.store_doc(), the code runs to completion and the get_model method has no issues. 
When I execute lm.extract_answer(), I noticed that the get_model() method, unlike in the case above, executes the lines of python below: 

`    elif not tokenizer_only:
        # Make sure the model is reloaded if we've unloaded it
        try:
            modelcache[model_name][1].load_model()
        except AttributeError:
            # Encoder-only models can't be unloaded in ctranslate2
            pass`

This then results in the following error being returned back 

Exception has occurred: AttributeError
'NoneType' object has no attribute 'generate_batch'
  File "C:\Users\ejmar\Documents\Eternev\ai_agent\languagemodels\languagemodels\inference.py", line 154, in generate_instruct
    results = model.generate_batch(
  File "C:\Users\ejmar\Documents\Eternev\ai_agent\languagemodels\languagemodels\__init__.py", line 189, in extract_answer
    return generate_instruct(f"{context}\n\n{question}")
  File "C:\Users\ejmar\Documents\Eternev\ai_agent\languagemodels\test.py", line 9, in <module>
    answer = lm.extract_answer(question=prompt, context=context)
AttributeError: 'NoneType' object has no attribute 'generate_batch'

I cloned your repo and ran `pip install -r requirements.txt`

Would you happen to know what the issue is? I have been trying to debug for the past couple of hours and all I can see is that the get_models method is returning None for the model, which I assume is the issue. 

I am working within the test.py file and I have included the project folder below. I would be super appreciative if you could help me debug since I am a huge fan of this project! 

[languagemodels.zip](https://github.com/jncraton/languagemodels/files/12178996/languagemodels.zip)

**Comment by TheChoicists** [comment]
I also want to add that when I run the the assistant.py file within the examples directory, that it works as expected but I need to run pip install languagemodels, which I believe means that it is using the files stored within the site-packages directory and those are the same files that are within the languagemodels directory that are within the zip I attached, which confuses me.

**Comment by TheChoicists** [comment]
Also, when I copied the files from the site-packages directory over into my languagemodels folder, I can now execute lm.do or lm.extract_answer without issue which confuses me but then again it also late 
![image](https://github.com/jncraton/languagemodels/assets/34602612/319afeb4-c218-490e-9edf-691c38fcd3f4)

**Comment by jncraton** [comment]
Thanks for letting me know about this. It looks like the main branch may not have been in a good state. I've merged several fixes from the dev branch just now, so hopefully these problems will be resolved for you. Let me know if you are still experiencing these issues after pulling down the updated code.

**Comment by TheChoicists** [comment]
Thank you for the quick turnaround! I tried cloning the repo today and when I tried to execute the assistant.py I got the following error: 
![image](https://github.com/jncraton/languagemodels/assets/34602612/c35d028d-84f1-4d6c-b166-6a1bf77e87b4)

Is this expected?

**Comment by jncraton** [comment]
That is not expected. It looks like the backend is detecting that CUDA is available via cuBLAS, but it isn't being initialized properly. I don't have a Windows environment handy at the moment, so I don't have an easy way to troubleshoot this with you, unfortunately.

I suspect that removing `device="auto"` from `initialize_model` in models.py will resolve this for you (by disabling CUDA).

**Comment by jncraton** [comment]
I've changed the default behavior to use the CPU unless CUDA detection is requested by setting `lm.config["device"] = "auto"`. This should hopefully resolve issues like this.

**Comment by TheChoicists** [comment]
That worked! Thank you so much! Are there any plans to implement larger models within this project? :)

**Comment by TheChoicists** [comment]
I noticed that the library is saying that cublas64_11.dll is not found or cannot be loaded but I checked my path variables and found that I do have cublas64_12.dll installed instead. 
![image](https://github.com/jncraton/languagemodels/assets/34602612/307e0d6a-cee6-403e-a0d9-043739ceacb9)

You had mentioned earlier that I resolve this by removing auto from the initialize_model method but what exactly would I need to change? 
![image](https://github.com/jncraton/languagemodels/assets/34602612/08ed7ba5-0b10-4f6a-be9f-7ebc353b3650)

**Comment by TheChoicists** [comment]
Got it! That makes sense, I tried pulling in the latest changes and we are all systems go! As for supporting future models, that makes sense. I am currently unblocked! Thank you for all of your help!
