### ISSUE TITLE
AttributeError: module 'languagemodels' has no attribute 'chat'

### ISSUE THREAD

**Issue by NormVg** [jncraton/languagemodels#29]
Been trying to run this lib in termux and it just keep showing this msgs 
![Screenshot_20240213-122241](https://github.com/jncraton/languagemodels/assets/87635928/d4f8a5ac-14ed-4e07-b59f-574cf1c55398)
![Screenshot_20240213-122318](https://github.com/jncraton/languagemodels/assets/87635928/837def0f-e514-465c-8650-1d3bd76ee10e)

**Comment by jncraton** [comment]
Could you confirm if your device (and termux) is running on ARMv7 (32-bit) or ARM64? There's no support for 32-bit devices in this package at the moment. If this package is working at all for you on a 32-bit device, it is likely using a very old version of the package.
