### ISSUE TITLE
store response in variable

### ISSUE THREAD

**Issue by mycomedico** [jncraton/languagemodels#30]
How do I store the model's response in a variable.  When I tried to do this I received the error:

`SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='?
`

**Comment by jncraton** [comment]
Most of the inference functions will simply return a string, so you can assign the result to a variable as follows:

```python
import languagemodels as lm

response = lm.do("What is the capital of France?")

print(response)
```

**Comment by mycomedico** [comment]
when i tried

`var1 = lm.extract_answer('question to llm')`

it yielded the error:

`SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='?
`

**Comment by jncraton** [comment]
Sounds good. I'm glad that you were able to get this resolved.
