### ISSUE TITLE
Support portuguese

### ISSUE THREAD

**Issue by thegabrielbee** [jncraton/languagemodels#36]
Can you explain if it`s possible to extend the lib to another language, like portuguese?

**Comment by thegabrielbee** [comment]
@jncraton Do you know some strategy to fit the model into your knowledge?

Because the model is being pretty lazy trying to resolve the context.

In the first question the response should be something like -> Esses sao seus casos Caso-1, Caso-2
Then the second one -> Esses sao seus casos Prioritarios Caso-P1, Caso-P2

Would be a pleasure for me to colaborate with your library, if you can give some instructions and orientations.

```python
import languagemodels as lm

lm.config['instruct_model'] = 'Llama-3.2-1B-Instruct'

def assist(question):
   context = lm.get_doc_context(question)
   return lm.do(f"Answer using context: {context} Question: {question}")


lat, lon = (41.8, -87.6)

lm.store_doc("Esses sao seus casos Caso-1, Caso-2", "casos")
lm.store_doc("Esses sao seus casos Prioritarios Caso-P1, Caso-P2", "casos prioritarios")

questions = [
    "Quais sao meus casos?",
    "Quais sao meus casos prioritarios?",
]

for question in questions:
    print(f"{question} -> {assist(question)}")
```

**Comment by jncraton** [comment]
If you're using the built-in vector DB for retrieving context, you'll also want to use an embedding model that is trained on Portuguese. I've added `multilingual-e5-small` that should work better than the default English-only model. You'll need to install from the dev branch (`pip install -q git+https://github.com/jncraton/languagemodels.git@dev`) in order to access it currently.

Here's your updated example (also available as a [Colab notebook](https://colab.research.google.com/drive/1FcPbUkJSGUlxEBHpHYkdq6UvOzBgWDF8)):

```python
import languagemodels as lm

lm.config['instruct_model'] = 'Llama-3.2-1B-Instruct'
lm.config['embedding_model'] = 'multilingual-e5-small'

def assist(question):
   context = lm.get_doc_context(question)
   return lm.do(f"Answer using context: {context} Question: {question}")


lat, lon = (41.8, -87.6)

lm.store_doc("Esses sao seus casos Caso-1, Caso-2", "casos")
lm.store_doc("Esses sao seus casos Prioritarios Caso-P1, Caso-P2", "casos prioritarios")

questions = [
    "Quais sao meus casos?",
    "Quais sao meus casos prioritarios?",
]

for question in questions:
    print(f"{question} -> {assist(question)}")
```

**Comment by thegabrielbee** [comment]
It keeps returning invalid messages like "Sorry for the error" or out-of-context messages using lm.chat...

In english it works well... do you have any recommendation? Like, how can i trains my own model.

**Comment by jncraton** [comment]
I'm not surprised that the `chat` function isn't working well for you. It's not very robust even in English. This package is used primarily for single-turn prompts using `do`, and we'll probably rework the `chat` endpoint for the 1.0 release.

This package does not support model training, but there are a lot of other resources available to learn about this. Andrej Karpathy's [Neural Networks: Zero to Hero](https://karpathy.ai/zero-to-hero.html) and [nanoGPT](https://github.com/karpathy/nanoGPT) wouldn't be a bad place to start.
