### ISSUE TITLE
Is there any recommended Chinese models (from huggingface)?

### ISSUE THREAD

**Issue by LeoWood** [jncraton/languagemodels#8]
when i input Chinese, like:
 **lm.do("你好")**
 it returns ' ⁇ , ⁇ , ⁇ '

It seems that the current model does not support Chinese
Is there any recommended Chinese models in huggingface?

**Comment by jncraton** [comment]
The models used here were trained and fine-tuned primarily in English, so other languages will not work well. I do not have plans to support multilingual models in this package at the moment, but there are some available on Hugging Face. Here's one example:

https://huggingface.co/bigscience/mt0-large
